# Generated by Django 4.2.5 on 2023-09-20 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.TextField(max_length=200)),
                ('status', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=200)),
                ('userid', models.TextField(max_length=200)),
                ('paswod', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizname', models.TextField(max_length=200)),
                ('no_of_quest', models.IntegerField(null=True)),
                ('quizDuration', models.TextField(max_length=20)),
                ('status', models.IntegerField(null=True)),
                ('courseId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.courses')),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500)),
                ('optA', models.TextField(max_length=200)),
                ('optB', models.TextField(max_length=200)),
                ('optC', models.TextField(max_length=200)),
                ('optD', models.TextField(max_length=200)),
                ('correctOpt', models.TextField(max_length=200)),
                ('courseId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.courses')),
                ('quizId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.quizz')),
            ],
        ),
    ]
