# Generated by Django 4.2.5 on 2023-09-21 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAns', models.TextField(max_length=200)),
                ('courseId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.courses')),
                ('questionId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.questions')),
                ('quizId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.quizz')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.user_login')),
            ],
        ),
    ]
