# Generated by Django 4.2.5 on 2023-09-21 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_useranswer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='quizz',
            new_name='courseQuizz',
        ),
    ]
