# Generated by Django 4.2.5 on 2023-09-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_quizz_coursequizz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursequizz',
            name='quizDuration',
            field=models.DurationField(null=True),
        ),
    ]
