# Generated by Django 4.2.5 on 2023-09-26 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_coursequizz_quizduration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='questionId',
        ),
    ]
