# Generated by Django 4.2.5 on 2023-10-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_useranswer_questionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_login',
            name='user_type',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
