# Generated by Django 4.2.5 on 2023-10-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_user_login_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_login',
            name='user_type',
            field=models.IntegerField(null=True),
        ),
    ]
